networks:
  devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

volumes:
  pgdata:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  prometheus-data:
  grafana-data:
  loki-data:

services:
  app:
    build: .
    container_name: dev_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devdb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpass
    networks:
      - devnet
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15-alpine
    container_name: dev_postgres
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devnet
    ports:
      - "5432:5432"

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: localhost
    # profiles:
    #   - manual
    networks:
      - devnet
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        registry_external_url 'http://gitlab.local:5050'
        gitlab_rails['registry_enabled'] = true
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    ports:
      - "8081:80"
      - "2224:22"

  prometheus:
    image: prom/prometheus:latest
    container_name: dev_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - devnet

  grafana:
    image: grafana/grafana:latest
    container_name: dev_grafana
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    networks:
      - devnet

  loki:
    image: grafana/loki:2.8.2
    container_name: dev_loki
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - devnet
