version: "3.8"

networks:
  devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

volumes:
  pgdata:

services:
  app:
    build: .
    container_name: dev_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devdb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpass
    networks:
      - devnet
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15-alpine
    container_name: dev_postgres
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - devnet
    ports:
      - "5432:5432"
