global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "spring-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app:8080"]

  - job_name: "gitlab"
    static_configs:
      - targets: ["gitlab:9090"]
